### PR TITLE
🌐(translations) fix translations issues in fr-FR.json

### PR DESCRIPTION
**Pull request by RaoufCherif**
## Purpose
Fix translations issue

## Body

Improve a few french translations issues in the fr-Fr.json

### CODE REVIEW

**Comment by Moustique82** [comment]
line 61: Salle publique --> espace virtuelle publique
line 101 : Reglages --> Paramètres
line 107 : Réglage salle --> Paramètres espace virtuelle

**Comment by jbpenrath** [comment]
@RaoufCherif, I updated translation message on crowdin (the platform on which we are translating messages) then download and compile translations through the command `make i18n-download-and-compile`.

I push a fixup commit to your PR. Review then squash it.

**Comment by RaoufCherif** [comment]
Hi,
I've squashed and fixed the lint tests. 
However there are still some back tests failing and I might have missed something but it doesn't seems related to my PR. Do you know if it'll be fixed or do you want me to fix them in this PR ?

**Comment by jbpenrath** [comment]
> Hi, I've squashed and fixed the lint tests. However there are still some back tests failing and I might have missed something but it doesn't seems related to my PR. Do you know if it'll be fixed or do you want me to fix them in this PR ?

Yup, we are aware about this issue. It has been fixed within the PR #223

**Review by PanchoutNathan — APPROVED** [review]

**Comment by jbpenrath** [comment]
@RaoufCherif, the issue has been fixed. Update our branch then you will be able to merge your PR 🥳

**Pull request merged**
